apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ky3se1rhz-go-gitops
  description: This is GitOps manifest for ky3se1rhz-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ky3se1rhz-go
    backstage.io/kubernetes-id: ky3se1rhz-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ky3se1rhz-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ky3se1rhz-go
