apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ky3se1rhz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ky3se1rhz-go 
  name: ky3se1rhz-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ky3se1rhz-go
    weight: 100 
