apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ky3se1rhz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ky3se1rhz-go 
  name: ky3se1rhz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ky3se1rhz-go 
